Eda notebook 
- to understand the data some prior to update the dataset
- get an idea on how many rows will be dropped and nulls in the data

In [1]:
import pandas as pd 
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

In [2]:
big_nss = pd.read_csv("../data/big_nss.csv")
big_nss.head()

C:\Users\blond\AppData\Local\Temp\ipykernel_72352\3568697817.py:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  big_nss = pd.read_csv("../data/big_nss.csv")

,Unnamed: 0,RecordID,EventTimeStamp,EquipmentID,EngineOilPressure,EngineOilTemperature,DistanceLtd,FuelLtd,EngineTimeLtd,Derate
0,0,1211417,2000-03-18 19:14:10,2015,25.52,190.85,274765.4,37866.421934,5673.1,False
1,1,1211418,2000-03-18 19:14:10,2015,25.52,190.85,274765.4,37866.421934,5673.1,False
2,2,1211419,2000-03-18 19:20:47,2015,NaN,NaN,NaN,NaN,NaN,False
3,3,1211420,2000-03-18 19:20:47,2015,NaN,NaN,NaN,NaN,NaN,False
4,4,1211422,2000-03-19 02:59:58,1849,NaN,NaN,NaN,NaN,NaN,False

In [3]:
big_nss.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1187335 entries, 0 to 1187334
Data columns (total 10 columns):
 #   Column                Non-Null Count    Dtype
---  ------                --------------    -----
 0   Unnamed: 0            1187335 non-null  int64
 1   RecordID              1187335 non-null  int64
 2   EventTimeStamp        1187335 non-null  object
 3   EquipmentID           1187335 non-null  object
 4   EngineOilPressure     586244 non-null   float64
 5   EngineOilTemperature  583912 non-null   float64
 6   DistanceLtd           585819 non-null   float64
 7   FuelLtd               585195 non-null   float64
 8   EngineTimeLtd         581366 non-null   float64
 9   Derate                1187335 non-null  bool
dtypes: bool(1), float64(5), int64(2), object(2)
memory usage: 82.7+ MB

In [4]:
# null counts per column before any changes
print(f"Total rows: {len(big_nss)}")
print("\nNull counts per column:")
big_nss.isna().sum()

Total rows: 1187335

Null counts per column:

Unnamed: 0                   0
RecordID                     0
EventTimeStamp               0
EquipmentID                  0
EngineOilPressure       601091
EngineOilTemperature    603423
DistanceLtd             601516
FuelLtd                 602140
EngineTimeLtd           605969
Derate                       0
dtype: int64

In [5]:
# rows where both oil columns AND all 3 ltd columns are null
oil_cols = ['EngineOilPressure', 'EngineOilTemperature']
ltd_cols = ['DistanceLtd', 'FuelLtd', 'EngineTimeLtd']

mask = big_nss[oil_cols].isna().all(axis=1) & big_nss[ltd_cols].isna().all(axis=1)
print(f"Rows to be dropped: {mask.sum()}")

Rows to be dropped: 599700

In [6]:

all_null_per_equipment = big_nss.groupby('EquipmentID')[ltd_cols].apply(lambda g: g.isna().all())
bad_ids = all_null_per_equipment[all_null_per_equipment.sum(axis=1) >= 2].index

print(f"Equipment IDs to drop: {len(bad_ids)}")
print(f"Rows to drop: {big_nss[big_nss['EquipmentID'].isin(bad_ids)].shape[0]}")

Equipment IDs to drop: 33
Rows to drop: 73

In [7]:
# checking on non altered dataset since the check i had said there were no rows updating and it seemed odd

has_some = big_nss[ltd_cols].notna().any(axis=1)
has_missing = big_nss[ltd_cols].isna().any(axis=1)

print(f"Rows with at least 1 Ltd value but missing others: {(has_some & has_missing).sum()}")

Rows with at least 1 Ltd value but missing others: 8652

In [9]:
with pd.option_context('display.max_rows', None):
    display(big_nss[big_nss['EquipmentID'] == 301])

,Unnamed: 0,RecordID,EventTimeStamp,EquipmentID,EngineOilPressure,EngineOilTemperature,DistanceLtd,FuelLtd,EngineTimeLtd,Derate
66977,66977,68495,2015-05-28 08:07:38,301,NaN,NaN,NaN,NaN,NaN,False
67432,67432,68953,2015-05-28 13:31:41,301,51.620000,215.206300,125989.2,17776.401551,2475.90,False
67566,67566,69086,2015-05-28 15:12:40,301,NaN,NaN,NaN,NaN,NaN,False
69830,69830,71663,2015-05-31 05:27:55,301,NaN,NaN,NaN,NaN,NaN,False
70009,70009,71844,2015-05-31 11:48:43,301,NaN,NaN,NaN,NaN,NaN,False
70010,70010,71845,2015-05-31 11:48:45,301,NaN,NaN,NaN,NaN,NaN,False
75861,75861,77719,2015-06-05 05:39:28,301,NaN,NaN,NaN,NaN,NaN,False
79600,79600,81434,2015-06-09 05:56:20,301,NaN,NaN,NaN,NaN,NaN,False
79615,79615,81446,2015-06-09 06:05:49,301,NaN,NaN,NaN,NaN,NaN,False
81283,81283,83119,2015-06-10 11:55:42,301,53.940000,201.706300,129342.4,18232.758771,2556.90,False
81304,81304,83139,2015-06-10 12:13:16,301,NaN,NaN,NaN,NaN,NaN,False
84884,84884,86722,2015-06-14 05:16:36,301,NaN,NaN,NaN,NaN,NaN,False
88957,88957,90793,2015-06-17 14:16:42,301,53.940000,217.906300,131495.0,18537.084975,2609.45,False
89035,89035,90871,2015-06-17 15:18:11,301,NaN,NaN,NaN,NaN,NaN,False
92667,92667,94501,2015-06-21 11:28:13,301,NaN,NaN,NaN,NaN,NaN,False
92668,92668,94502,2015-06-21 11:28:14,301,NaN,NaN,NaN,NaN,NaN,False
107323,107323,109162,2015-07-03 05:06:52,301,NaN,NaN,NaN,NaN,NaN,False
110428,110428,113745,2015-07-07 05:56:08,301,62.060000,93.875000,136685.3,19234.499192,2718.90,False
111918,111918,113746,2015-07-08 05:12:15,301,NaN,NaN,NaN,NaN,NaN,False
112195,112195,114029,2015-07-08 08:38:13,301,59.160000,217.175000,136831.8,19255.897128,2721.45,False
112304,112304,114136,2015-07-08 09:49:17,301,NaN,NaN,NaN,NaN,NaN,False
117766,117766,119608,2015-07-13 05:00:00,301,NaN,NaN,NaN,NaN,NaN,False
117767,117767,119609,2015-07-13 05:00:44,301,62.060000,97.137500,138005.4,19408.192316,2745.35,False
117768,117768,119610,2015-07-13 05:02:11,301,NaN,NaN,NaN,NaN,NaN,False
128769,128769,130619,2015-07-21 13:53:33,301,53.940000,219.706300,141193.5,19833.509320,2808.30,False
128956,128956,130804,2015-07-21 15:05:17,301,NaN,NaN,NaN,NaN,NaN,False
134434,134434,136275,2015-07-25 05:22:09,301,NaN,NaN,NaN,NaN,NaN,False
140272,140272,142118,2015-07-29 10:06:56,301,NaN,NaN,NaN,NaN,NaN,False
145425,145425,147273,2015-08-02 05:17:58,301,NaN,NaN,NaN,NaN,NaN,False
145813,145813,147664,2015-08-02 13:50:14,301,58.000000,214.700000,144559.8,20271.638668,2870.35,False
145946,145946,147795,2015-08-02 16:22:55,301,NaN,NaN,NaN,NaN,NaN,False
155244,155244,157092,2015-08-09 06:31:51,301,24.360000,204.800000,146663.9,20559.718291,2912.70,False
155370,155370,157219,2015-08-09 09:27:04,301,27.260000,187.700000,146756.3,20571.341861,2915.05,False
155396,155396,157244,2015-08-09 09:51:14,301,NaN,NaN,NaN,NaN,NaN,False
163031,163031,164878,2015-08-13 15:48:03,301,55.100000,213.406300,148342.6,20790.340492,2951.25,False
163278,163278,165124,2015-08-13 16:47:32,301,NaN,NaN,NaN,NaN,NaN,False
171376,171376,173222,2015-08-19 11:41:19,301,NaN,NaN,NaN,NaN,NaN,False
171377,171377,173223,2015-08-19 11:41:21,301,NaN,NaN,NaN,NaN,NaN,False
171661,171661,173509,2015-08-19 14:23:49,301,52.780000,205.868700,149739.9,20974.468413,2985.30,False
171739,171739,173585,2015-08-19 15:21:50,301,NaN,NaN,NaN,NaN,NaN,False
173022,173022,174866,2015-08-20 13:09:43,301,56.840000,209.975000,150201.9,21036.945103,2993.65,False
175967,175967,177817,2015-08-23 05:05:12,301,NaN,NaN,NaN,NaN,NaN,False
177095,177095,178940,2015-08-24 08:25:33,301,NaN,NaN,NaN,NaN,NaN,False
177096,177096,178941,2015-08-24 08:25:35,301,NaN,NaN,NaN,NaN,NaN,False
177559,177559,179408,2015-08-24 13:28:41,301,NaN,NaN,NaN,NaN,NaN,False
179330,179330,181181,2015-08-25 16:09:48,301,51.040000,211.606200,151728.1,21246.433540,3022.70,False
179381,179381,181232,2015-08-25 16:56:20,301,NaN,NaN,NaN,NaN,NaN,False
199417,199417,201265,2015-09-12 09:56:21,301,1.160000,70.700000,156486.2,21892.598379,3125.45,False
199418,199418,201266,2015-09-12 09:59:05,301,NaN,NaN,NaN,NaN,NaN,False
199419,199419,201267,2015-09-12 09:59:10,301,NaN,NaN,NaN,NaN,NaN,False
199420,199420,201269,2015-09-12 10:00:26,301,1.160000,70.700000,156486.2,21892.598379,3125.45,False
199423,199423,201272,2015-09-12 10:05:40,301,NaN,NaN,NaN,NaN,NaN,False
208794,208794,210641,2015-09-20 12:08:04,301,25.520000,204.406300,158417.4,22169.318604,3171.60,False
208796,208796,210643,2015-09-20 12:10:22,301,NaN,NaN,NaN,NaN,NaN,False
242829,242829,246114,2015-10-18 09:11:54,301,23.780000,197.206300,164335.5,22970.684524,3303.50,False
242835,242835,246120,2015-10-18 09:18:33,301,NaN,NaN,NaN,NaN,NaN,False
259742,259742,263022,2015-11-02 05:34:03,301,63.800000,77.000000,168831.6,23585.809147,3396.45,False
259743,259743,263023,2015-11-02 05:35:48,301,NaN,NaN,NaN,NaN,NaN,False
260191,260191,263481,2015-11-02 12:07:04,301,1.160000,NaN,168945.7,23603.112416,3399.95,False
260202,260202,263487,2015-11-02 12:11:20,301,NaN,NaN,NaN,NaN,NaN,False
267161,267161,270450,2015-11-08 07:41:52,301,36.540000,190.906300,170470.8,23802.430229,3434.50,False
267191,267191,270479,2015-11-08 08:14:15,301,NaN,NaN,NaN,NaN,NaN,False
268903,268903,272230,2015-11-10 05:06:57,301,63.800000,72.275000,171051.5,23885.644426,3447.25,False
268950,268950,272232,2015-11-10 05:56:34,301,NaN,NaN,NaN,NaN,NaN,False
270164,270164,273453,2015-11-11 04:58:14,301,64.960000,64.737500,171528.9,23952.479955,3455.65,False
270165,270165,273454,2015-11-11 05:00:04,301,NaN,NaN,NaN,NaN,NaN,False
271745,271745,275033,2015-11-12 06:21:33,301,30.160000,187.700000,172013.1,24014.560387,3464.25,False
271746,271746,275035,2015-11-12 06:21:38,301,29.580000,188.375000,172013.1,24014.560387,3464.25,False
271757,271757,275043,2015-11-12 06:27:45,301,NaN,NaN,NaN,NaN,NaN,False
271983,271983,275267,2015-11-12 08:38:11,301,46.980000,208.400000,172129.9,24031.071140,3466.50,False
272190,272190,275474,2015-11-12 10:40:57,301,NaN,NaN,NaN,NaN,NaN,False
272193,272193,275478,2015-11-12 10:42:32,301,NaN,NaN,NaN,NaN,NaN,False
275104,275104,278393,2015-11-15 05:10:37,301,75.980000,48.200000,172490.6,24080.999658,3473.15,False
275106,275106,278394,2015-11-15 05:13:20,301,NaN,NaN,NaN,NaN,NaN,False
311512,311512,316039,2015-12-17 14:32:29,301,1.740000,178.475000,180915.1,25241.243311,3661.50,False
311513,311513,316040,2015-12-17 14:32:33,301,1.160000,178.137500,180915.1,25241.243311,3661.50,False
311534,311534,316059,2015-12-17 14:50:02,301,NaN,NaN,NaN,NaN,NaN,False
311535,311535,316060,2015-12-17 14:50:02,301,NaN,NaN,NaN,NaN,NaN,False
314456,314456,318982,2015-12-19 23:00:01,301,5.800000,69.800000,180930.5,25243.620859,3662.20,False
314457,314457,318983,2015-12-19 23:06:31,301,NaN,NaN,NaN,NaN,NaN,False
315095,315095,319622,2015-12-20 15:31:16,301,84.680000,110.468800,181057.5,25265.811311,3666.90,False
315199,315199,319727,2015-12-20 19:01:30,301,NaN,NaN,NaN,NaN,NaN,False
318935,318935,323457,2015-12-23 16:46:08,301,62.060000,108.106200,182076.2,25401.595746,3688.35,False
318940,318940,323461,2015-12-23 16:49:28,301,NaN,NaN,NaN,NaN,NaN,False
319077,319077,323600,2015-12-24 01:02:07,301,34.220000,184.775000,182461.8,25450.335490,3695.65,False
319630,319630,324157,2015-12-26 05:03:12,301,NaN,NaN,NaN,NaN,NaN,False
348564,348564,354600,2016-01-21 06:46:06,301,81.780000,130.437500,189453.1,26504.117805,3851.25,False
348728,348728,354762,2016-01-21 08:50:55,301,NaN,NaN,NaN,NaN,NaN,False
353896,353896,359933,2016-01-26 11:44:37,301,29.580000,NaN,190452.5,26654.431703,3877.75,False
353897,353897,359934,2016-01-26 11:44:39,301,29.580000,159.237500,190452.5,26654.431703,3877.75,False
353906,353906,359940,2016-01-26 11:49:09,301,NaN,NaN,NaN,NaN,NaN,False
353907,353907,359941,2016-01-26 11:49:11,301,NaN,NaN,NaN,NaN,NaN,False
360427,360427,367393,2016-02-01 11:42:45,301,24.940000,205.306200,192116.0,26884.129302,3910.95,False
360443,360443,367411,2016-02-01 11:49:02,301,NaN,NaN,NaN,NaN,NaN,False
381780,381780,388760,2016-02-18 13:54:44,301,26.680000,199.175000,196603.5,27539.540163,4002.50,False
381790,381790,388762,2016-02-18 13:59:46,301,NaN,NaN,NaN,NaN,NaN,False
388046,388046,395017,2016-02-24 10:05:42,301,45.820000,205.868700,198036.8,27740.046750,4029.90,False
388189,388189,395162,2016-02-24 11:40:34,301,NaN,NaN,NaN,NaN,NaN,False
414426,414426,422169,2016-03-20 05:08:11,301,73.079990,49.606250,203010.1,28421.478559,4122.10,False
414427,414427,422170,2016-03-20 05:08:11,301,73.079990,49.606250,203010.1,28421.478559,4122.10,False
414428,414428,422168,2016-03-20 05:08:11,301,73.079990,49.606250,203010.1,28421.478559,4122.10,False
414429,414429,422171,2016-03-20 05:09:51,301,NaN,NaN,NaN,NaN,NaN,False
414431,414431,422173,2016-03-20 05:10:11,301,NaN,NaN,NaN,NaN,NaN,False
414465,414465,422208,2016-03-20 06:43:56,301,NaN,NaN,NaN,NaN,NaN,False
418470,418470,426212,2016-03-24 06:08:50,301,24.360000,198.106200,204787.3,28675.612073,4159.00,False
418474,418474,426214,2016-03-24 06:10:26,301,NaN,NaN,NaN,NaN,NaN,False
428325,428325,436073,2016-04-03 15:25:53,301,35.380000,195.575000,207786.2,29088.116732,4224.40,False
428326,428326,436074,2016-04-03 15:25:58,301,26.680000,196.137500,207786.2,29088.116732,4224.40,False
428334,428334,436082,2016-04-03 15:46:45,301,NaN,NaN,NaN,NaN,NaN,False
428335,428335,436083,2016-04-03 15:46:45,301,NaN,NaN,NaN,NaN,NaN,False
433720,433720,441465,2016-04-08 10:35:18,301,54.520000,180.837500,209458.8,29321.644826,4260.35,False
433777,433777,441525,2016-04-08 11:19:47,301,NaN,NaN,NaN,NaN,NaN,False
442208,442208,449957,2016-04-17 05:59:18,301,62.060000,189.668700,211678.3,29629.141094,4306.15,False
442209,442209,449956,2016-04-17 05:59:18,301,62.060000,189.668700,211678.3,29629.141094,4306.15,False
442210,442210,449958,2016-04-17 05:59:37,301,25.520000,188.375000,211678.5,29629.141094,4306.15,False
442213,442213,449962,2016-04-17 06:05:00,301,24.360000,201.200000,211680.3,29629.405266,4306.25,False
442236,442236,449985,2016-04-17 07:05:14,301,NaN,NaN,NaN,NaN,NaN,False
442353,442353,450099,2016-04-17 09:54:40,301,1.160000,101.075000,211680.3,29629.405266,4306.25,False
442383,442383,450125,2016-04-17 10:30:25,301,NaN,NaN,NaN,NaN,NaN,False
442384,442384,450124,2016-04-17 10:30:25,301,NaN,NaN,NaN,NaN,NaN,False
442403,442403,450150,2016-04-17 10:55:57,301,NaN,NaN,NaN,NaN,NaN,False
442404,442404,450151,2016-04-17 10:55:57,301,NaN,NaN,NaN,NaN,NaN,False
445992,445992,454597,2016-04-20 15:49:07,301,26.100000,195.068800,213158.2,29820.269574,4333.80,False
446001,446001,454598,2016-04-20 16:01:23,301,NaN,NaN,NaN,NaN,NaN,False
449387,449387,457979,2016-04-24 10:22:06,301,26.100000,191.300000,213749.3,29897.936157,4346.60,False
449388,449388,457980,2016-04-24 10:22:10,301,25.520000,192.875000,213749.3,29897.936157,4346.60,False
449392,449392,457985,2016-04-24 10:32:49,301,NaN,NaN,NaN,NaN,NaN,False
449393,449393,457986,2016-04-24 10:32:49,301,NaN,NaN,NaN,NaN,NaN,False
461961,461961,470551,2016-05-08 07:18:37,301,25.520000,200.806200,215310.0,30111.783433,4379.30,False
461974,461974,470566,2016-05-08 07:44:08,301,NaN,NaN,NaN,NaN,NaN,False
461993,461993,470585,2016-05-08 08:16:27,301,27.260000,196.700000,215342.9,30116.406444,4380.15,False
462010,462010,470601,2016-05-08 08:46:02,301,NaN,NaN,NaN,NaN,NaN,False
462026,462026,470619,2016-05-08 09:13:52,301,24.940000,203.900000,215371.5,30119.708595,4380.90,False
462031,462031,470621,2016-05-08 09:24:41,301,NaN,NaN,NaN,NaN,NaN,False
462046,462046,470638,2016-05-08 09:58:15,301,24.360000,201.706300,215389.3,30122.350315,4381.40,False
462049,462049,470641,2016-05-08 10:06:36,301,NaN,NaN,NaN,NaN,NaN,False
462061,462061,470654,2016-05-08 10:43:00,301,24.940000,200.806200,215393.5,30123.274918,4381.80,False
462406,462406,471001,2016-05-09 05:12:48,301,NaN,NaN,NaN,NaN,NaN,False
462408,462408,471003,2016-05-09 05:12:58,301,62.640000,85.606250,215393.7,30123.407004,4381.90,False
462422,462422,471016,2016-05-09 05:55:25,301,NaN,NaN,NaN,NaN,NaN,False
463492,463492,472082,2016-05-10 06:19:22,301,28.420000,178.137500,215829.9,30176.373500,4390.15,False
463514,463514,472104,2016-05-10 06:40:40,301,NaN,NaN,NaN,NaN,NaN,False
464800,464800,473395,2016-05-11 10:23:45,301,29.580000,170.768800,216477.0,30261.040643,4401.70,False
464932,464932,473528,2016-05-11 12:58:08,301,24.940000,203.900000,216608.3,30278.343912,4404.15,False
465050,465050,473661,2016-05-11 15:22:22,301,NaN,NaN,NaN,NaN,NaN,False
465364,465364,473955,2016-05-12 05:02:45,301,62.060000,92.637500,216740.2,30296.439698,4406.55,False
465365,465365,473957,2016-05-12 05:04:50,301,NaN,NaN,NaN,NaN,NaN,False
465427,465427,474019,2016-05-12 06:24:33,301,26.100000,198.106200,216762.3,30298.949332,4407.15,False
465452,465452,474045,2016-05-12 07:05:03,301,NaN,NaN,NaN,NaN,NaN,False
465495,465495,474086,2016-05-12 07:44:58,301,24.940000,205.868700,216796.5,30302.779827,4408.05,False
465503,465503,474093,2016-05-12 07:54:16,301,NaN,NaN,NaN,NaN,NaN,False
465514,465514,474123,2016-05-12 08:05:57,301,29.580000,196.137500,216811.0,30304.364859,4408.35,False
465775,465775,474371,2016-05-12 12:09:40,301,NaN,NaN,NaN,NaN,NaN,False
465796,465796,474392,2016-05-12 12:30:13,301,24.940000,205.868700,217027.7,30329.461204,4412.50,False
465961,465961,474554,2016-05-12 15:27:50,301,NaN,NaN,NaN,NaN,NaN,False
466058,466058,474653,2016-05-12 17:25:19,301,27.840000,200.806200,217245.8,30358.255958,4416.85,False
467712,467712,476306,2016-05-14 21:49:08,301,NaN,NaN,NaN,NaN,NaN,False
467824,467824,476417,2016-05-15 05:50:26,301,45.240000,133.700000,217284.7,30364.331915,4418.15,False
467908,467908,476501,2016-05-15 09:16:25,301,NaN,NaN,NaN,NaN,NaN,False
467951,467951,476545,2016-05-15 10:43:43,301,26.100000,208.006300,217563.8,30400.127228,4422.85,False
467955,467955,476547,2016-05-15 10:53:40,301,NaN,NaN,NaN,NaN,NaN,False
468045,468045,476638,2016-05-15 13:49:28,301,25.520000,197.600000,217585.8,30403.693551,4423.75,False
468116,468116,476710,2016-05-15 16:54:16,301,NaN,NaN,NaN,NaN,NaN,False
468315,468315,476911,2016-05-16 05:04:15,301,63.220000,81.275000,217731.3,30424.431057,4426.85,False
468365,468365,476956,2016-05-16 05:55:15,301,NaN,NaN,NaN,NaN,NaN,False
468553,468553,477144,2016-05-16 09:54:29,301,25.520000,200.300000,217944.1,30457.188391,4430.70,False
468574,468574,477166,2016-05-16 10:15:13,301,NaN,NaN,NaN,NaN,NaN,False
468767,468767,477361,2016-05-16 13:55:05,301,22.040000,208.906300,218074.6,30476.340865,4433.35,False
468897,468897,477506,2016-05-16 16:12:41,301,NaN,NaN,NaN,NaN,NaN,False
469233,469233,477836,2016-05-17 04:59:29,301,62.060000,90.668750,218202.1,30494.964995,4435.60,False
469247,469247,477837,2016-05-17 05:13:25,301,NaN,NaN,NaN,NaN,NaN,False
470699,470699,479295,2016-05-18 12:07:54,301,25.520000,200.300000,218224.0,30498.399231,4436.15,False
470730,470730,479324,2016-05-18 12:33:15,301,NaN,NaN,NaN,NaN,NaN,False
471303,471303,479922,2016-05-19 05:17:08,301,64.960000,73.400000,218338.3,30512.004092,4438.85,False
471329,471329,479923,2016-05-19 05:55:31,301,NaN,NaN,NaN,NaN,NaN,False
471366,471366,479958,2016-05-19 06:30:55,301,26.680000,188.037500,218348.9,30513.721210,4439.25,False
471415,471415,480005,2016-05-19 07:23:26,301,NaN,NaN,NaN,NaN,NaN,False
471562,471562,480159,2016-05-19 09:44:56,301,28.420000,200.806200,218451.5,30525.608953,4441.55,False
471570,471570,480167,2016-05-19 09:57:09,301,NaN,NaN,NaN,NaN,NaN,False
471591,471591,480204,2016-05-19 10:13:29,301,24.940000,199.175000,218456.6,30526.533555,4441.90,False
471646,471646,480241,2016-05-19 10:46:13,301,NaN,NaN,NaN,NaN,NaN,False
471698,471698,480293,2016-05-19 11:26:21,301,21.460000,202.268800,218507.2,30533.137856,4443.00,False
471710,471710,480303,2016-05-19 11:37:24,301,NaN,NaN,NaN,NaN,NaN,False
471728,471728,480345,2016-05-19 11:50:29,301,25.520000,201.706300,218511.8,30534.062458,4443.35,False
471794,471794,480379,2016-05-19 12:27:17,301,NaN,NaN,NaN,NaN,NaN,False
471855,471855,480446,2016-05-19 13:13:17,301,25.520000,198.106200,218546.3,30538.685469,4444.40,False
471858,471858,480450,2016-05-19 13:17:36,301,NaN,NaN,NaN,NaN,NaN,False
471897,471897,482418,2016-05-19 13:46:36,301,25.520000,199.175000,218561.6,30540.534674,4444.85,False
473823,473823,482419,2016-05-22 05:17:33,301,NaN,NaN,NaN,NaN,NaN,False
473835,473835,482432,2016-05-22 06:06:17,301,29.580000,178.868700,218568.3,30541.987620,4445.30,False
473836,473836,482433,2016-05-22 06:11:20,301,NaN,NaN,NaN,NaN,NaN,False
473891,473891,482485,2016-05-22 07:44:46,301,26.100000,200.300000,218596.6,30546.346459,4446.30,False
473927,473927,482525,2016-05-22 09:02:56,301,NaN,NaN,NaN,NaN,NaN,False
474027,474027,482625,2016-05-22 12:01:52,301,24.940000,205.868700,218747.8,30565.234761,4449.20,False
474035,474035,482633,2016-05-22 12:05:47,301,NaN,NaN,NaN,NaN,NaN,False
474038,474038,482641,2016-05-22 12:10:39,301,NaN,NaN,NaN,NaN,NaN,False
474052,474052,482656,2016-05-22 12:29:34,301,24.940000,202.775000,218760.9,30567.083965,4449.60,False
474097,474097,482688,2016-05-22 13:44:13,301,NaN,NaN,NaN,NaN,NaN,False
474116,474116,482711,2016-05-22 14:02:50,301,29.580000,193.268800,218811.9,30573.424094,4451.00,False
474155,474155,482751,2016-05-22 15:27:15,301,NaN,NaN,NaN,NaN,NaN,False
474165,474165,482762,2016-05-22 15:49:29,301,24.940000,205.868700,218823.2,30575.933729,4452.00,False
474179,474179,482776,2016-05-22 16:25:49,301,NaN,NaN,NaN,NaN,NaN,False
474194,474194,482789,2016-05-22 17:00:21,301,26.100000,203.337500,218875.7,30583.858890,4453.15,False
474195,474195,482790,2016-05-22 17:03:34,301,NaN,NaN,NaN,NaN,NaN,False
474374,474374,482970,2016-05-23 06:27:37,301,24.940000,195.068800,218913.2,30589.406503,4454.40,False
474382,474382,482975,2016-05-23 06:37:16,301,NaN,NaN,NaN,NaN,NaN,False
474445,474445,483034,2016-05-23 07:40:33,301,22.040000,197.600000,218943.7,30593.104912,4455.15,False
474481,474481,483073,2016-05-23 08:21:21,301,NaN,NaN,NaN,NaN,NaN,False
474580,474580,483176,2016-05-23 10:13:22,301,24.940000,205.306200,219000.3,30600.633815,4456.35,False
474599,474599,483195,2016-05-23 10:21:47,301,NaN,NaN,NaN,NaN,NaN,False
474620,474620,483226,2016-05-23 10:38:49,301,25.520000,198.668700,219007.5,30601.558418,4456.75,False
474690,474690,483278,2016-05-23 11:44:19,301,NaN,NaN,NaN,NaN,NaN,False
474771,474771,483365,2016-05-23 12:54:05,301,25.520000,201.200000,219036.0,30605.785170,4457.55,False
474789,474789,483384,2016-05-23 13:25:43,301,NaN,NaN,NaN,NaN,NaN,False
474798,474798,483393,2016-05-23 13:36:29,301,25.520000,196.137500,219060.5,30608.823149,4458.20,False
474836,474836,483428,2016-05-23 14:17:47,301,NaN,NaN,NaN,NaN,NaN,False
474855,474855,483447,2016-05-23 14:45:09,301,24.940000,199.175000,219102.8,30614.899106,4459.20,False
474876,474876,483469,2016-05-23 14:56:50,301,NaN,NaN,NaN,NaN,NaN,False
474943,474943,483538,2016-05-23 16:27:06,301,24.940000,204.800000,219137.3,30620.050461,4460.60,False
474948,474948,483545,2016-05-23 16:38:24,301,NaN,NaN,NaN,NaN,NaN,False
475284,475284,483879,2016-05-24 06:39:21,301,25.520000,199.737500,219180.7,30626.918935,4461.70,False
475288,475288,483882,2016-05-24 06:44:45,301,NaN,NaN,NaN,NaN,NaN,False
475440,475440,484033,2016-05-24 09:32:10,301,22.040000,193.268800,219186.9,30628.503967,4462.30,False
475488,475488,484081,2016-05-24 10:17:24,301,NaN,NaN,NaN,NaN,NaN,False
475595,475595,484188,2016-05-24 11:37:32,301,26.680000,192.537500,219232.8,30635.372440,4463.75,False
475690,475690,484283,2016-05-24 12:54:56,301,NaN,NaN,NaN,NaN,NaN,False
475711,475711,484304,2016-05-24 13:10:03,301,25.520000,201.706300,219238.2,30637.221645,4465.20,False
475722,475722,484324,2016-05-24 13:20:46,301,NaN,NaN,NaN,NaN,NaN,False
475752,475752,484347,2016-05-24 13:49:34,301,25.520000,203.900000,219263.7,30640.523795,4465.80,False
475761,475761,484356,2016-05-24 14:02:37,301,NaN,NaN,NaN,NaN,NaN,False
475881,475881,484472,2016-05-24 15:55:28,301,22.040000,202.268800,219319.0,30648.845215,4467.55,False
475940,475940,484534,2016-05-24 16:59:03,301,NaN,NaN,NaN,NaN,NaN,False
475955,475955,484551,2016-05-24 17:17:21,301,21.460000,206.937500,219362.3,30654.260742,4468.75,False
475961,475961,484556,2016-05-24 17:21:02,301,NaN,NaN,NaN,NaN,NaN,False

In [8]:
print(big_nss[(big_nss['EquipmentID'] == '301')])

         Unnamed: 0  RecordID       EventTimeStamp EquipmentID  \
1108           1108       561  2015-02-22 05:03:32         301
1109           1109       560  2015-02-22 05:03:32         301
1110           1110       559  2015-02-22 05:03:32         301
18133         18133     18465  2015-04-10 15:53:35         301
29649         29649     30246  2015-04-22 05:14:49         301
...             ...       ...                  ...         ...
1047520     1047520   1089011  2018-12-03 17:05:12         301
1047523     1047523   1089014  2018-12-03 17:08:54         301
1047524     1047524   1089013  2018-12-03 17:08:54         301
1047525     1047525   1088988  2018-12-03 17:08:54         301
1047526     1047526   1088987  2018-12-03 17:08:54         301

         EngineOilPressure  EngineOilTemperature  DistanceLtd       FuelLtd  \
1108                   NaN                   NaN          NaN           NaN
1109                   NaN                   NaN          NaN           NaN
1110                   NaN                   NaN          NaN           NaN
18133                  NaN                   NaN          NaN           NaN
29649                  NaN                   NaN          NaN           NaN
...                    ...                   ...          ...           ...
1047520               29.0              200.8062     384443.3  53591.791673
1047523                NaN                   NaN          NaN           NaN
1047524                NaN                   NaN          NaN           NaN
1047525                NaN                   NaN          NaN           NaN
1047526                NaN                   NaN          NaN           NaN

         EngineTimeLtd  Derate
1108               NaN   False
1109               NaN   False
1110               NaN   False
18133              NaN   False
29649              NaN   False
...                ...     ...
1047520        8840.65   False
1047523            NaN   False
1047524            NaN   False
1047525            NaN   False
1047526            NaN   False

[244 rows x 10 columns]